#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int T1 = 0;
	int threshold = 20;
	bool flag = true;
	while(true){
		flag = true;

		if(getColorReflected(S2) < threshold){
			if(getColorReflected(S3) < threshold){
					resetTimer(T1);
				while(getTimer(T1, milliseconds) < 250){
					motor[motorB] = 50;
					motor[motorC] = 50;
			}
			}
			else{
				motor[motorB] = 0;
				motor[motorC] = 60;
			}
		}
		if(getColorReflected(S3) < threshold){
			if(getColorReflected(S2) < threshold){
					resetTimer(T1);
				while(getTimer(T1, milliseconds) < 250){
					motor[motorB] = 50;
					motor[motorC] = 50;
			}
			}
			else{
				motor[motorC] = 0;
				motor[motorB] = 60;
			}
		}
		if(getColorReflected(S1) < threshold){
			flag = false;
			resetTimer(T1);
			while(getTimer(T1, milliseconds) < 150){
				motor[motorB] = -50;
				motor[motorC] = 50;
			}
		}
		if(getColorReflected(S4) < threshold){
			flag = false;
			resetTimer(T1);
			while(getTimer(T1, milliseconds) < 150){
				motor[motorC] = -50;
				motor[motorB] = 50;
			}
		}
		if(flag){
			motor[motorB] = 50;
			motor[motorC] = 50;
	}
	}
}
