#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int threshold = 50;
	while(true){
		if(getColorReflected(S2) < threshold){
			if(getColorReflected(S3) < threshold){
				motor[motorB] = 60;
				motor[motorC] = 60;
			}
			else{
				motor[motorB] = 0;
				motor[motorC] = 50;
			}
		}
		if(getColorReflected(S3) < threshold){
			if(getColorReflected(S2) < threshold){
				motor[motorB] = 60;
				motor[motorC] = 60;
			}
			else{
				motor[motorC] = 0;
				motor[motorB] = 50;
			}
		}
		if(getColorReflected(S1) < threshold){
			motor[motorB] = -50;
			motor[motorC] = 100;
		}
		if(getColorReflected(S1) < threshold){
			motor[motorC] = -50;
			motor[motorB] = 100;
		}

		else{
			motor[motorB] = 60;
			motor[motorC] = 60;
		}
	}
}
